### PR TITLE
fix localjumperror for network devices

### PR DESCRIPTION
**Pull request by jaredstehler**
### Description

Adds `nfs4` as type to exclude from device-wait, fix that block.

### Issues Resolved

https://github.com/sous-chefs/filesystem/issues/34

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/filesystem/35)

### CODE REVIEW

**Comment by rshade** [comment]
should we create an nfs4 server and do a connection in a test?

**Comment by damacus** [comment]
We could do. It'd be pretty easy using something like [this](https://github.com/atomic-penguin/cookbook-nfs/blob/master/test/kitchen/cookbooks/nfs_test/recipes/issue46.rb)

**Comment by rshade** [comment]
that is what I am thinking then 127.0.0.1 mount it.

**Comment by rshade** [comment]
@jaredstehler would you be willing to take a crack at that?

**Comment by mattlqx** [comment]
Can this be merged? The cookbook just doesn't work for network filesystems without this and it's been sitting for almost 9 months.

**Comment by MarkGibbons** [comment]
@mattlqx I'll see if I can write a test tonight.

**Comment by mattlqx** [comment]
I actually see now that even with this pull applied, network filesystems don't get mounted with this resource. https://github.com/sous-chefs/filesystem/blob/master/providers/default.rb#L263 :\

**Comment by damacus** [comment]
I'm going to close this down for now. 

If you can rebase on current master and drop some tests in that'd be great!

**Pull request closed without merging**
