### PR TITLE
Update mount permissions upon mounting.

### PR DESCRIPTION
**Pull request by donwlewis**
Reference issue #33

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/filesystem/37)

### CODE REVIEW

**Comment by rshade** [comment]
@donwlewis, thank you for your contribution. I am going to fix those lint errors in another branch then will update yours

**Comment by rshade** [comment]
@donwlewis can you update your branch?

**Comment by donwlewis** [comment]
Updated.

**Comment by rshade** [comment]
thankis @donwlewis

**Pull request merged**
