### PR TITLE
Add input validation for label property

### PR DESCRIPTION
**Pull request by jasonwbarnett**
# Description

`mkfs.xfs` has a maximum of 12 characters for the label (`-L`).

Ideally this would be merged after https://github.com/sous-chefs/filesystem/pull/105

## Issues Resolved

N/A

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by damacus** [comment]
Looks like we're blocked on LVM being updated. 

I've just move it across to Sous-Chefs so it needs adopting and fixing to work with Chef 17

**Comment by jasonwbarnett** [comment]
@damacus I opened this up: https://github.com/sous-chefs/lvm/pull/210

**Comment by ramereth** [comment]
@jasonwbarnett can you please fix the issue on this PR? I rebased it and the other issues are fixed

**Comment by jasonwbarnett** [comment]
@damacus thanks for handling this 🚀. Totally dropped off my radar.

**Comment by damacus** [comment]
Mine too! My inbox is just a mess so I'm glad I found this nice PR to apply 😂

**Comment by tr3pan** [comment]
According to `man mkfs.ext4` 

>        -L new-volume-label
>              Set the volume label for the file system to new-volume-label.  The maximum length of the volume label is 16 bytes.

`ext4` max label length can be 2 characters longer than `xfs`.

**Pull request merged**
